---
title: "Loops and Functions"
author: "Erika"
date: "2022-08-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```

## Loop

### Task 1
```{r}
weekdays <- c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday")
transects <- c("Transect A", "Transect B", "Transect C")

out_matrix <- matrix(nrow = length(weekdays), ncol = length(transects))

for (i in seq_along(weekdays)) {
  for (j in seq_along(transects)) {
    val <- paste(weekdays[i], "-", transects[j])
    out_matrix[i, j] <- val # Store the value in the appropriate row & column
  }
}
```

## Functions

### Task 2
```{r}
force <- function(mass, acceleration) {
  num <- mass * acceleration
  print(paste("The resulting force is", num, "Newtons."))
}

force(3, 2)
```

### Task 3
```{r}
fish_parms <- data.frame(
  sci_name = c("Chanos chanos", "Sphyraena barracuda", "Caranx ignobilis"),
  common_name = c("Milkfish", "Great barracuda", "Giant trevally"),
  a_est = c(0.0905, 0.0181, 0.0353),
  b_est = c(2.52, 3.27, 3.05)
)

fish_weight <- function(fish_name, tot_length) {
  my_fish <- filter(fish_parms, common_name == fish_name)
  weight <- my_fish$a_est * tot_length ** my_fish$b_est
  print(weight)
}

milkfish_weights <- fish_weight("Milkfish", 0:100)
```

## Task 4
```{r}
wave_power <- function(wave_height, period) {
  power <- 0.5 * (wave_height ** 2) * period
  print(power)
}

my_heights <- seq(from = 0, to = 3, by = 0.2)
my_period <- 8

wave_power(my_heights, my_period)
```

## Task 5
```{r}
wave_power_complex <- function(water_depth, wave_height, period) {
  if (water_depth > 12) {
    power <- 0.5 * (wave_height ** 2) * period
    print(power)
    message("Deep water equation used")
  }
  if (water_depth <= 12) {
    power <- 0.81 * (wave_height ** 2) * period
    print(power)
    message("Shallow water equation used")
  }
}

my_heights <- seq(from = 0, to = 3, by = 0.2)
my_period <- 8

wave_power_complex(11, my_heights, my_period)
wave_power_complex(13, my_heights, my_period)
```

